thelook_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: thelook-pipeline
      dataset: thelook
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
      timeout_seconds: 300
      location: US
